# -*- coding: utf-8 -*-
"""Cross validation17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1MUmmh1zKi03bk0qzLZ-KkxYn9q8QZO
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_score

# Load dataset from CSV
df = pd.read_csv("/content/cross_validation_dataset.csv")

# Features and Target
X = df[["Hours_Studied", "Sleep_Hours", "Attendance(%)"]]
y = df["Passed"]

# Classifiers
clf1 = DecisionTreeClassifier(random_state=42)
clf2 = LogisticRegression(max_iter=1000)

# K-Fold
k_folds = KFold(n_splits=10, shuffle=True, random_state=42)

# Cross Validation
scores1 = cross_val_score(clf1, X, y, cv=k_folds)
scores2 = cross_val_score(clf2, X, y, cv=k_folds)

# Print results
print("Decision Tree CV Scores: ", scores1)
print("Logistic Regression CV Scores: ", scores2)

print("Average CV Score (Decision Tree): ", scores1.mean())
print("Average CV Score (Logistic Regression): ", scores2.mean())

print("Number of CV Scores used (Decision Tree): ", len(scores1))
print("Number of CV Scores used (Logistic Regression): ", len(scores2))