# -*- coding: utf-8 -*-
"""Simple linear regression17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMKjNoiYnk3lPNedBkB_4C2dZz1bbdC7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
data={
    'X' : [18,22,23,26,28,31,33],
    'y' : [10000,15000,18000,21000,24000,26500,27000]
}
df=pd.DataFrame(data)
X=df[['X']]
y=df['y']
model=LinearRegression()
model.fit(X,y)
y_pred=model.predict(X)
print("Slope (m):", model.coef_[0])
print("Intercept (c):", model.intercept_)
plt.scatter(X,y,color='blue',label='Actual')
plt.plot(X,y_pred,color='red',label='Regression Line')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Simple Linear Regression')
plt.legend()
plt.show()